# Generated by Django 3.2.9 on 2021-12-21 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partition',
            options={'ordering': ['name'], 'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
        migrations.AlterField(
            model_name='task',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='task',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='task', verbose_name='Чертеж'),
        ),
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='math_app.level', verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='task',
            name='numclass',
            field=models.IntegerField(default=0, verbose_name='класс'),
        ),
        migrations.AlterField(
            model_name='task',
            name='numtask',
            field=models.IntegerField(default=0, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='task',
            name='question',
            field=models.TextField(blank=True, verbose_name='Условие'),
        ),
        migrations.AlterField(
            model_name='task',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='math_app.theme', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='task',
            name='variant',
            field=models.IntegerField(default=0, verbose_name='Вариант'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(max_length=512),
        ),
    ]
